providers = ["node"]

[node]
pkgs = ["...", "google-chrome"]

[phases.setup]
aptPkgs = [
    "libcairo2", 
    "libgbm1", 
    "libnss3", 
    "libatk1.0-0", 
    "libatk-bridge2.0-0", 
    "libcups2", 
    "libdrm2", 
    "libxkbcommon0", 
    "libxcomposite1", 
    "libxdamage1", 
    "libxext6", 
    "libxfixes3", 
    "libxrandr2", 
    "libasound2t64", 
    "libxcb1",           # Tambahan opsional tapi krusial untuk Chromium baru
    "libpango-1.0-0", 
    "libpangocairo-1.0-0", 
    "libgdk-pixbuf2.0-0", 
    "libglib2.0-0"
]
